language: en
pipeline:
  - name: SpacyNLP
    model: spacy.word2vec.model
  - name: SpacyTokenizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 20
    random_seed: 1234
  - name: EntitySynonymMapper
  
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#   - name: RulePolicy
